let realAnimals = [
  {
    id: 1,
    name: "New Moon",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-0.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 2,
    name: "New Moon",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-0.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 3,
    name: "Waxing Crecsent",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-35.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 4,
    name: "Waxing Crecsent",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-35.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 5,
    name: "First Quater",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-54.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 6,
    name: "First Quater",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-54.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 7,
    name: "Waxing Gibbous",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-73.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 8,
    name: "Waxing Gibbous",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-73.png",
    isPushed: false,
    outOfGame: false,
    flip: true,
  },
  {
    id: 9,
    name: "Full Moon",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-100.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 10,
    name: "Full Moon",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-100.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 11,
    name: "Waning Gibbous",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-73.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 12,
    name: "Waning Gibbous",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-73.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 13,
    name: "Last Quater",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-54.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 14,
    name: "Last Quater",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-54.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 15,
    name: "Waning Crecsent",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-35.png",
    isPushed: false,
    outOfGame: false,
  },
  {
    id: 16,
    name: "Waning Crecsent",
    photo: "https://nineplanets.org/static/lib/astro/images/shadow-35.png",
    isPushed: false,
    outOfGame: false,
  },
];

realAnimals = realAnimals.sort(() => 0.5 - Math.random());

export default realAnimals;
